"""empty message

Revision ID: 466119528f1e
Revises: None
Create Date: 2014-02-23 00:08:07.277514

"""

# revision identifiers, used by Alembic.
revision = '466119528f1e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('md5_url', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'md5_url')
    ### end Alembic commands ###
